language: ruby
rvm:
- 2.1.1

cache: bundler

install: gem install bundler -v 1.11.2 && bundle install
script: bundle_path=$(which bundle) && sed -i -e "s/activate_bin_path/bin_path/g" $bundle_path && bundle exec rake site:deploy --trace

# branch whitelist, only for GitHub Pages
branches:
  only:
  - /pages-(.*)/ # test every branch which starts with "pages-"


sudo: false # route your build to the container-based infrastructure for a faster build
