# Site settings
title: 'Gheorghiță BUTNARU'
description: 'System and Network Engineer @ &#34;Gh. Asachi&#34; Technical University of Iasi<br>'
description_url: 'http://www.tuiasi.ro'
second_description: 'AWS Certified Solutions Architect – Associate<br>'
second_description_url: 'https://www.certmetrics.com/amazon/public/badge.aspx?i=1&t=c&d=2017-02-21&ci=AWS00192670'
third_description: 'Huawei Certified Network Associate<br>'
third_description_url: 'http://gbutnaru.me/images/HCNA_010100101679806850931409.pdf'
url: 'https://gbutnaru.me'
enforce_ssl: 'gbutnaru.me'
baseurl: '/'
google_analytics: 'UA-98624101-1'
# disqus_shortname: 'gbutnaru'

author:
  name: 'Gheorghiță BUTNARU'
  email: contact@gbutnaru.me
  twitter_username: GheorghitaBU
# facebook_username:
  github_username:  Gheorghita
  linkedin_username:  gbutnaru
  linuxacademy_username: Gheorghita

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: ../website-data/
paginate: 10
permalink: /:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', '.travis.yml', 'Rakefile']

# Settings for deploy rake task
username:        Gheorghita
repo:            website
branch:          pages-source
relative_source: ../website/
destination_branch: gh-pages
destination_folder: ../website-data/
production_url:  https://gbutnaru.me
source_url:      https://github.com/Gheorghita/website
