# Site settings
title: Gheorghiță BUTNARU
description: 'System and Network Engineer @ "Gh. Asachi" Technical University of Iaşi'
url: 'http://gbutnaru.me'
baseurl: '/'
google_analytics: 'UA-98624101-1'
# disqus_shortname: 'gbutnaru'

author:
  name: 'Gheorghiță BUTNARU'
  email: contact@gbutnaru.me
  twitter_username: GheorghitaBU
#  facebook_username:
  github_username:  Gheorghita
  linkedin_username:  gbutnaru

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: ../website-data/
paginate: 10
permalink: /:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', '.travis.yml', 'Rakefile']

# Settings for deploy rake task
username:        Gheorghita
repo:            website
branch:          pages-source
relative_source: ../website/
destination_branch: gh-pages
destination_folder: ../website-data/
production_url:  https://gbutnaru.me
source_url:      https://github.com/Gheorghita/website
