# Site settings
title: Gheorghiță BUTNARU
description: 'System and Network Engineer @ "Gh. Asachi" Technical University of Iaşi'
url: 'gbutnaru.me'
baseurl: '/'
google_analytics: 'UA-98624101-1'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Gheorghiță BUTNARU'
  email: contact@gbutnaru.me
  twitter_username: GheorghitaBU
#  facebook_username: joshgerdes
  github_username:  Gheorghita
  linkedin_username:  gbutnaru

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
